#!/usr/bin/env python3

def bytes2chars(i):
    return ' '.join(chr(j) for j in range(i, i+32))

for i in range(32, 128, 32):
    if i < 64:
        print("%-25s %s" % ("Punctuation and digits:", bytes2chars(i)))
    elif i < 96:
        print("%-25s %s" % ("Uppercase letters: ", bytes2chars(i)))
    else:
        print("%-25s %s" % ("Lowecase letters: ", bytes2chars(i)))
